version: "2"
services:
  api:
    build: .
    ports:
      - "3000:3000"
    command: npm run start:dev
    volumes:
      - ./dist:/app/dist
    depends_on:
      - mongo
    env_file: .env

  mongo:
    image: mongo
    volumes:
      - /data/db
    ports:
      - "27017:27017"
    command: --smallfiles --logpath=/dev/null # --quiet
